export const APPWRITE_CONFIG = {
    ENDPOINT: process.env.EXPO_PUBLIC_APPWRITE_API_ENDPOINT,
    PROJECT_ID: process.env.EXPO_PUBLIC_APPWRITE_PROJECT_ID,
    DATABASE_ID: process.env.EXPO_PUBLIC_APPWRITE_DATABASE_ID,
    COLLECTION_ID: process.env.EXPO_PUBLIC_APPWRITE_COLLECTION_ID,
}